### PR TITLE
Should close session iso intending to

### PR DESCRIPTION
**Pull request by PashoQ**
This should resolve the issue of #344

### CODE REVIEW

**Comment by ahoy-jon** [comment]
@PashoQ Hey, thanks a lot. Sorry for the delay, I was in holidays.

Can we reproduce with a test? It looks promising

**Comment by PashoQ** [comment]
Sure. Should be easy to do. Should take me one or two days to do.

Thanks a lot.

**Comment by PashoQ** [comment]
Not really sure that I did it right, but it validates now that the session is closed after the scope is released.

**Comment by ahoy-jon** [comment]
Ok, I will take a look, a lot of tests are failing.

image

**Comment by ahoy-jon** [comment]
@PashoQ that's normal, it's not really testable without :

- forking the test in a new JVM
- doing some weird stuff with "SparkSession.clearActiveSession"
- mocking the sparkSession 
...
- force this test to run last after all the other tests that use a sparkSession

Currently, the test closes the activeSession, which is shared.

**Comment by ahoy-jon** [comment]
closed by https://github.com/univalence/zio-spark/pull/353

**Pull request closed without merging**
